scrum/board/urls.py
#!/usr/bin/env python
# encoding: utf-8

from rest_framework.routers import DefaultRouter

from . import views


router = DefaultRouter(trailing_slash=False)
router.register(r'sprints', views.SprintViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'users', views.UserViewSet)

scrum/scrum/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls import include, url
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from board.urls import router

urlpatterns = [
    url(r'^api/token', obtain_auth_token, name='api-token'),
    url(r'^api/', include(router.urls)),
    url(r'^$', TemplateView.as_view(template_name='board/index.html')),
]

scrum/board/models.py
#!/usr/bin/env python
# encoding: utf-8

from django.db import models
from django.conf import settings


class Sprint(models.Model):
    """ development iteration period """

    name = models.CharField(max_length=100, blank=True, default='')
    description = models.TextField(blank=True, default='')
    end = models.DateField(unique=True)

    def ___str__(self):
        return self.name or "Sprint ending %s" % self.end


class Task(models.Model):
    """ unit of work to be done for the sprint """

    STATUS_TODO = 1
    STATUS_IN_PROGRESS = 2
    STATUS_TESTING = 3
    STATUS_DONE = 4

    STATUS_CHOICES = (
        (STATUS_TODO, 'Not Started'),
        (STATUS_IN_PROGRESS, 'In Progress'),
        (STATUS_TESTING, 'Testing'),
        (STATUS_DONE, 'DONE'),
    )

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='')
    sprint = models.ForeignKey(Sprint, null=True, blank=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICES,
                                      default=STATUS_TODO)
    order = models.SmallIntegerField(default=0)
    assigned = models.ForeignKey(settings.AUTH_USER_MODEL,
                                 null=True, blank=True)
    started = models.DateField(blank=True, null=True)
    due = models.DateField(blank=True, null=True)
    completed = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

scrum/board/forms.py
#!/usr/bin/env python
# encoding: utf-8

from __future__ import unicode_literals

import django_filters
from django.contrib.auth import get_user_model

from .models import Task, Sprint


User = get_user_model()


class NullFilter(django_filters.BooleanFilter):
    """ filter on a field set as null or not """

    def filter(self, qs, value):
        if value is not None:
            return qs.filter(**{'%s__isnull' % self.name: value})

        return qs


class TaskFilter(django_filters.FilterSet):

    backlog = NullFilter(name='sprint')

    class Meta:
        model = Task
        fields = ('sprint', 'status', 'assigned', 'backlog',)

    def __init__(self, *args, **kw):
        super(TaskFilter, self).__init__(*args, **kw)
        self.filters['assigned'].extra.update(
            {'to_field_name': User.USERNAME_FIELD})


class SprintFilter(django_filters.FilterSet):

    end_min = django_filters.DateFilter(name="end", lookup_type='gte')
    end_max = django_filters.DateFilter(name="end", lookup_type='lte')

    class Meta:
        model = Sprint
        fields = ('end_min', 'end_max')

scrum/board/views.py
#!/usr/bin/env python
# encoding: utf-8

from rest_framework import viewsets
from rest_framework import authentication
from rest_framework import permissions
from rest_framework import filters
from django.contrib.auth import get_user_model

from .models import Sprint, Task
from .forms import TaskFilter, SprintFilter
from .serializers import SprintSerializer, TaskSerializer, UserSerializer


User = get_user_model()


class DefaultsMixin(object):
    """ default settings for view auth/permission """

    authentication_classes = (
        authentication.BasicAuthentication,
        authentication.TokenAuthentication,
    )
    permission_classes = (
        permissions.IsAuthenticated,
    )
    paginate_by = 2
    paginated_by_param = 'page_size'
    max_paginate_by = 7
    filter_backends = (
        filters.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )


class SprintViewSet(DefaultsMixin, viewsets.ModelViewSet):
    """ API endpoint for sprints """

    queryset = Sprint.objects.order_by('end')
    serializer_class = SprintSerializer
    filter_class = SprintFilter
    search_fields = ('name',)
    ordering_fields = ('end', 'name',)


class TaskViewSet(DefaultsMixin, viewsets.ModelViewSet):
    """ API for task """

    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    filter_class = TaskFilter
    search_fields = ('name', 'description',)
    ordering_fields = ('name', 'order', 'stared', 'due', 'completed',)


class UserViewSet(DefaultsMixin, viewsets.ReadOnlyModelViewSet):
    """ api for user """

    lookup_field = User.USERNAME_FIELD
    loopup_url_kwarg = User.USERNAME_FIELD
    queryset = User.objects.order_by(User.USERNAME_FIELD)
    serializer_class = UserSerializer
    search_fields = (User.USERNAME_FIELD,)

scrum/board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Scrum Board</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
  <link rel="stylesheet" href="{% static 'board/css/board.css' %}" >
  <script type='text/template' id='home-template'>
    <h2>Your sprints</h2>
    <button class="add" type="submit">Add Sprint</button>
    <% if (sprints !== null) { %>
      <div class="sprints">
        <% _.each(sprints.models, function(sprint){ %>
          <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
            <%- sprint.get('name') %><br>
            <span>DUE BY <%- sprint.get('end') %></span>
          </a>
        <% }); %>
      </div>
      <% else { %>
        <h3 class="loading">Loading ...</h3>
      <% } %>
  </script>
  <script type='text/template' id='login-template'>
    <form action="" method="post">
      <label for="id_username">Usernmae</label>
      <input id="id_username" type="text" name="username" maxlength="30" required />
      <label for="id_password">Password</label>
      <input id="id_password" type="password" name="password" required />
      <button type="submit">Login</button>
    </form>
  </script>
  <script type='text/template' id='header-template'>
    <span class="title">Scrum Board Example</span>
    <% if (authenticated) { %>
      <nav>
        <a href="/" class="button">Your Sprints</a>
        <a href="#" class="logout button">Logout</a>
      </nav>
    <% } %>
  </script>
  <script type='text/html' id='new-sprint-template'>
    <form action='' method='post'>
      <label for='id_name'>Sprint name</label>
      <input id='id_name' type='text' name='name' maxlength='100' required />
      <label for='id_end'>End Date</label>
      <input id='id_end' type='date' name='end' />
      <label for='id_description'>Description</label>
      <textarea id='id_description' name='description' cols='50'></textarea>
      <button class='cancle'>Cancel</button>
      <button class='submot'>Create</button>
    </form>
  </script>
  <script type='text/html' id='sprint-template'>
    <% if (sprint !== null) { %>
      <% if(!sprint.invalid) { %>
        <h2><%- sprint.get('name') %></h2>
        <span class="due-date">Due <%- sprint.get('end') %></span>
        <p class="description"><%- sprint.get('description') %.</p>
        <div class="tasks"></div>
      <% }else{ %>
        <h1>Sprint <%- sprint.get('id') %> not found.</h1>
      <% } %>
    <% } else { %>
        <h1 class="loading">Loading...</h1>
    <% } %>
  </script>
  <script type='text/html' id='status-template'>
    <h4><%- title %></h4>
    <div class="list"></div>
    <% if(sprint === null) { %>
      <button class="add" type="submit">Add Task</button>
    <% } %>
  </script>
  <script type='text/html' id='new-task-template'>
    <form class="add-task" action="" method="post">
      <label for="id_name">Task Name</label>
      <input id="id_name" type="text" name="name" maxlength="100" required />
      <label for="id_description">Description</label>
      <textarea id="id_description" name="description"></textarea>
      <button class="create" type="submot">Create</button>
      <button class="cancel" type="submit">Cancel</button>
  </script>
  <script type="text/html" id="task-item-template">
    <%- task.get('name') %>
  </script>
  <script type="text/html" id="task-detail-template">
    <div data-field="name" class="name" contenteditable="true">
      <%- task.get('name') %>
    </div>
    <div data-field="description" class="description" contenteditable="true">
      <%- task.get('description') %>
    </div>
    <div class="with-label">
      <div class="label">Due:</div>
      <div data-field="due" class="due date" contenteditable="true">
        <%- task.get('due') || empty %>
      </div>
    </div>
    <div class="with-label">
      <div class="label">Assigned To:</div>
      <div data-field="assigned" class="assigned" contenteditable="true">
        <%- task.get('assigned') || empty %>
      </div>
      <form>
        <button class="cancel" type="submit">Close</button>
        <button class="save" type="submit" hidden>Save</button>
      </form>
  </script>
</head>
<body>
  <div id="content"></div>

  <script src="{% static 'board/vendor/jquery-2.1.3.js' %}"></script>
  <script src="{% static 'board/vendor/underscore.js' %}"></script>
  <script src="{% static 'board/vendor/backbone.js' %}"></script>
  <script id="config" type="text/json">
    {
      "models": {},
      "collections": {},
      "views": {},
      "router": null,
      "apiRoot": "{% url 'api-root' %}",
      "apiLogin": "{% url 'api-token' %}"
    }
  </script>
  <script src="{% static 'board/js/app.js' %}"></script>
  <script src="{% static 'board/js/models.js' %}"></script>
  <script src="{% static 'board/js/views.js' %}"></script>
  <script src="{% static 'board/js/router.js' %}"></script>
</body>
</html>

scrum/scrum/board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Scrum Board</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
  <link rel="stylesheet" href="{% static 'board/css/board.css' %}" >
  <script type='text/template' id='home-template'>
    <h2>Your sprints</h2>
    <button class="add" type="submit">Add Sprint</button>
    <% if (sprints !== null) { %>
      <div class="sprints">
        <% _.each(sprints.models, function(sprint){ %>
          <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
            <%- sprint.get('name') %><br>
            <span>DUE BY <%- sprint.get('end') %></span>
          </a>
        <% }); %>
      </div>
      <% } else { %>
        <h3 class="loading">Loading ...</h3>
      <% } %>
  </script>
  <script type='text/template' id='login-template'>
    <form action="" method="post">
      <label for="id_username">Usernmae</label>
      <input id="id_username" type="text" name="username" maxlength="30" required />
      <label for="id_password">Password</label>
      <input id="id_password" type="password" name="password" required />
      <button type="submit">Login</button>
    </form>
  </script>
  <script type='text/template' id='header-template'>
    <span class="title">Scrum Board Example</span>
    <% if (authenticated) { %>
      <nav>
        <a href="/" class="button">Your Sprints</a>
        <a href="#" class="logout button">Logout</a>
      </nav>
    <% } %>
  </script>
  <script type='text/html' id='new-sprint-template'>
    <form action='' method='post'>
      <label for='id_name'>Sprint name</label>
      <input id='id_name' type='text' name='name' maxlength='100' required />
      <label for='id_end'>End Date</label>
      <input id='id_end' type='date' name='end' />
      <label for='id_description'>Description</label>
      <textarea id='id_description' name='description' cols='50'></textarea>
      <button class='cancle'>Cancel</button>
      <button class='submot'>Create</button>
    </form>
  </script>
  <script type='text/html' id='sprint-template'>
    <% if (sprint !== null) { %>
      <% if(!sprint.invalid) { %>
        <h2><%- sprint.get('name') %></h2>
        <span class="due-date">Due <%- sprint.get('end') %></span>
        <p class="description"><%- sprint.get('description') %></p>
        <div class="tasks"></div>
      <% }else{ %>
        <h1>Sprint <%- sprint.get('id') %> not found.</h1>
      <% } %>
    <% } else { %>
        <h1 class="loading">Loading...</h1>
    <% } %>
  </script>
  <script type='text/html' id='status-template'>
    <h4><%- title %></h4>
    <div class="list"></div>
    <% if(sprint === null) { %>
      <button class="add" type="submit">Add Task</button>
    <% } %>
  </script>
  <script type='text/html' id='new-task-template'>
    <form class="add-task" action="" method="post">
      <label for="id_name">Task Name</label>
      <input id="id_name" type="text" name="name" maxlength="100" required />
      <label for="id_description">Description</label>
      <textarea id="id_description" name="description"></textarea>
      <button class="create" type="submot">Create</button>
      <button class="cancel" type="submit">Cancel</button>
  </script>
  <script type="text/html" id="task-item-template">
    <%- task.get('name') %>
  </script>
  <script type="text/html" id="task-detail-template">
    <div data-field="name" class="name" contenteditable="true">
      <%- task.get('name') %>
    </div>
    <div data-field="description" class="description" contenteditable="true">
      <%- task.get('description') %>
    </div>
    <div class="with-label">
      <div class="label">Due:</div>
      <div data-field="due" class="due date" contenteditable="true">
        <%- task.get('due') || empty %>
      </div>
    </div>
    <div class="with-label">
      <div class="label">Assigned To:</div>
      <div data-field="assigned" class="assigned" contenteditable="true">
        <%- task.get('assigned') || empty %>
      </div>
      <form>
        <button class="cancel" type="submit">Close</button>
        <button class="save" type="submit" hidden>Save</button>
      </form>
  </script>
</head>
<body>
  <div id="content"></div>

  <script src="{% static 'board/vendor/jquery-2.1.3.js' %}"></script>
  <script src="{% static 'board/vendor/underscore.js' %}"></script>
  <script src="{% static 'board/vendor/backbone.js' %}"></script>
  <script id="config" type="text/json">
    {
      "models": {},
      "collections": {},
      "views": {},
      "router": null,
      "apiRoot": "{% url 'api-root' %}",
      "apiLogin": "{% url 'api-token' %}"
    }
  </script>
  <script src="{% static 'board/js/app.js' %}"></script>
  <script src="{% statis 'board/js/socket.js' %}"></script>
  <script src="{% static 'board/js/models.js' %}"></script>
  <script src="{% static 'board/js/views.js' %}"></script>
  <script src="{% static 'board/js/router.js' %}"></script>
</body>
</html>